apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: eks-example
    region: ap-southeast-2

nodeGroups:
    - name: spot-instances
      minSize: 2
      maxSize: 10
      instancesDistribution:
        instanceTypes: ["t3.medium", "m4.large", "m5.large"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 3
      labels:
        lifecycle: Ec2Spot
        intent: apps
      taints:
        spotInstance: "true:PreferNoSchedule"
      iam:
        withAddonPolicies:
          autoScaler: true
          cloudWatch: true
          albIngress: true