---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: k8s.gcr.io/cluster-autoscaler:v1.13.7
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --nodes=2:10:<INSERT-YOUR-SPOT-INSTANCES-ASG-NAME-HERE>
            - --expander=random
            - --expendable-pods-priority-cutoff=-10
            - --scale-down-unneeded-time=30s
            - --scale-down-unready-time=30s
            - --scale-down-delay-after-add=30s
            - --scale-down-utilization-threshold=0.7
            - --balance-similar-node-groups
            - --max-total-unready-percentage=75
            - --ok-total-unready-count=20
            - --max-empty-bulk-delete=30
          env:
            - name: AWS_REGION
              value: ap-southeast-2
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
